name: LaTeX

on: push

jobs:
  pdfLaTeX:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        apt-get update
        apt-get install -y python3 zip bzip2
    - name: zip up the sources
      run: |
        zip -9 -Z bzip2 -r -x '.git/*' @ .github/workflows/payload .
    - name: compile
      run: |
        latexmk -pdf ctufit-thesis.tex
        makeglossaries ctufit-thesis
        latexmk -pdf ctufit-thesis.tex
    - name: turn into a polyglot
      run: |
        git clone --recursive --depth 1 --branch lua-script-hack https://github.com/viluon/truepolyglot.git
        truepolyglot/truepolyglot pdfzip \
          --pdffile ctufit-thesis.pdf \
          --luafile .github/workflows/payload.lua \
          --zipfile .github/workflows/payload.zip \
          ./poly.pdf
        chmod +x poly.pdf
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pdfs
        path: '*.pdf'
    - name: release
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        # Git tag (for automatic releases)
        automatic_release_tag: latest
        # Should this release be marked as a draft?
        prerelease: false
        # Release title (for automatic releases)
        title: thesis preview
        # Assets to upload to the release
        files: |
          ctufit-thesis.pdf
          poly.pdf
