name: LaTeX

on: push

jobs:
  pdfLaTeX:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive
    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: latexmk -pdf ctufit-thesis.tex
    - name: release
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        # Git tag (for automatic releases)
        automatic_release_tag: latest
        # Should this release be marked as a draft?
        prerelease: false
        # Release title (for automatic releases)
        title: thesis preview
        # Assets to upload to the release
        files: |
          ctufit-thesis.pdf
