name: Docker container
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  slim:
    runs-on: ubuntu-latest
    steps:
    - name: login to ${{ env.REGISTRY }}
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build a docker container
      uses: docker/build-push-action@v4
      with:
        file: .github/workflows/Dockerfile
        push: false
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest

    - name: checkout
      uses: actions/checkout@v3

    - name: slim it
      uses: viluon/docker-slim-action@v5
      env:
        DSLIM_HTTP_PROBE: false
        DSLIM_INCLUDE_SHELL: true
        DSLIM_SHOW_CLOGS: true
        DSLIM_SHOW_BLOGS: true
        DSLIM_PLOG: true
        DSLIM_RC_ENTRYPOINT: /app/.github/workflows/build.sh
      with:
        target: ${{ env.REGISTRY }}/${{ github.repository }}:latest
        tag: "slim"

    - name: push to the registry
      run: docker image push "${{ env.REGISTRY }}/${{ github.repository }}" --all-tags
